spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: driver
    password: 0209ahc@
    url: jdbc:mysql://localhost:3306/greendrive?useSSL=false&serverTimezone=Asia/Seoul
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
